### ISSUE TITLE
PCB production parameters

### ISSUE THREAD

**Issue by kavanozz** [HenrykRichter/A500KB#1]
I am interested in your projects, looks very good. Can you please provide the preferred parameters used in the production of the PCBs? Probably most important one is the tickness.

**Comment by HenrykRichter** [comment]
My apologies for the late answer. I've had the main PCBs built with 1.6mm thickness and the plates with 1mm. As an afterthought, 1.2mm would probably have been better for the plates.

In scenarios where only the main PCB is desired (like for Cherry switches with mounting pin), a higher thickness >= 2mm would be a good choice.
