### ISSUE TITLE
RGB led examples

### ISSUE THREAD

**Issue by kavanozz** [HenrykRichter/A500KB#3]
Hi Henryk,

I ordered a few partially assembled PCBs to JLC. I picked this RGB led for D1, 5, 6, 7, 51, 52, 53 but they said it doesn't fit in there.
https://www.lcsc.com/product-detail/Light-Emitting-Diodes-LED_MEIHUA-MHPA3528RGBCT_C409779.html

I will hand solder them. Can you please give some examples from Mouser/Digikey or some other vendor?

For the plate RBG leds (APA102 5050), are these the correct ones?
https://www.sparkfun.com/products/14863

Thanks

**Comment by HenrykRichter** [comment]
Yes, the pads were drawn with hand soldering in mind as a middle ground between analog LEDs with leads and PLCC type LEDs. I had Würth LEDs in mind (order# 150141M173100).

Please don't populate the plate when using the assembly in original Amiga 2000/3000/4000 keyboard cases or A500's. The plate will touch the keyboard cover and pinch LEDs mounted there. For that reason, firmware and software support for these extra LEDs was not implemented.
