### ISSUE TITLE
A1200 compatibility

### ISSUE THREAD

**Issue by jcagigal** [HenrykRichter/A500KB#7]
Hi! As a feature request for the next revisions perhaps you could make It also A1200 compatible performing some small changes to make the small controller board dettachable so the main keyboard part fits in an A1200 case. Or maybe just splitting the big leds using a few pins/connector allowing the user to "dettach" the leds part if he's going to use an A1200.

Perhaps allowing to solder a connector like 32way Molex 52044-3245 underside so a long flat cable like Molex 15168-0400 can be connected to A1200 connector. One of the extra connections could be cut down from the flat cable so It fits into the A1200 keyboard connector.

Anyway great job. It would be cool if you could post pictures using standard cherry keycaps too. What do you think about using a 3d printed mitsumi-low profile cherry adapter to use original keys?

**Comment by HenrykRichter** [comment]
From my perspective, the A1200 is out of scope. It's certainly possible to modify the existing PCB layout by removing the controller section. Then again, my main motivation (besides the use of mechanical keys) was to get something simlar to BiFrost on A500s. If you are looking for an A1200 Keyboard, there already is the approach by Aeberbach (https://github.com/aeberbach/A1200KB).

Concerning adapters: Some years back I built a custom Amiga keyboard using 3D printed adapters to fit Mitsumi A500 keycaps to Alps keys. While (surprisingly) the adapters work fine and the keys still feel natural and klick happily, the added height made it unsuitable for classic enclosures. My conclusion was that probably the better option would be to replicate the Cherry stem with a Mitsumi compatible opening and modify Cherry keys with those. I'm unsure if resin printed parts would be strong enough. As far as I've read, at least two people have looked at this route (Phil from A1200.net, Kipper on EAB). That being said: The low profile switches may still fit with an adapter but I didn't try.
